sudo: false
dist: trusty
language: python
cache: pip
python:
  - 2.7
  - 3.5
  - 3.6
matrix:
  include:
  - python: 2.7
    env: TOXENV=lint
install:
  - pip install tox-travis
  - pip install .
script:
  - ros-get -h
  - tox
