dist: bionic
language: python
cache: pip
python:
  - 2.7
  - 3.5
  - 3.6
matrix:
  include:
    - env: description=xenial
      dist: xenial
      python: 2.7
    - env: TOXENV=lint
      python: 2.7
install:
  - pip install tox-travis
  - pip install .
script:
  - ros-get -h
  - tox
deploy:
  provider: pypi
  user: Rayman
  password:
  - secure: "fDa5xY47dRFwETjcliltO/ns7NTVmwsm0kNQUppbp0UxkMow64zRrQZpY3KqktNFJVF76G5tuJ75Qu67ouwTNeC5BtxsMqv7FNrqWQfhw0lSwLwgkixnLahSboOQ+sn5BJzklPsOyU8JH/0fBnRmKqtQMUkzbILsLgcKlkWFV6PxpVonyQGIQnlwDXLR84MJiyB1q2Le5BrbJq8rviOSik7wX6B6CaXNlX9MrtTV68Ane7d7TcRKvmFnrXjn+Ojtmk+BHrlpuvonr2mxDfoVjzuSgIIPWbnt893vE8Gf+NnR0iQ2KpkrbtVoCrtvfC3IqmqmCKRzC074xxGmNdQucaoUTdHUn807KlZc4MyW6ZcOCJt5Mo3EjnZT2ZDN5Iq28gz+DO4WjdrceHByv8A+sC/FvdZsiH9ZEIAlK3ahtiPePPOBcxhe+Sg717W3Rd4xsaKNeI+yVm5BNk/fDt/A8NAtnYfuU/LY4eFefNiPePVbT2C+36DwhzzAeH4qLDgPQRKBqAEZkm/WOzKqSaH8LW5QZ+B1bGIeW/gUiG2rqwmxoi1jTyoPaWBBTrFAChEPFwZuV87QcWtG5x7pG2V0W3AmWUYqmQCH5ApYb8Zw4uLFq7Ib16NbveEkfvR3YrS6zGewu6vxg4xsdBk7fjUYQxwhYgb4R4OzCYJ+CXiZ+PY="
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: $TOXENV = lint
