#!/bin/bash

CONFIG_PATH=$HOME/.config/ros-get
WS_CONFIG=$CONFIG_PATH/workspaces

mkdir -pv $CONFIG_PATH
mkdir -pv $WS_CONFIG

case $1 in
    create)
        if [[ -z "$2" ]]
        then
            echo "$0: missing argument workspace NAME"
        else
            if [[ -d "src" ]]
            then
                ln -sv "$PWD" "$WS_CONFIG/$2"
            else
                echo "$0: not in a ROS workspace"
            fi
        fi
        ;;
    *)
        echo "$0: unrecognized option '$1'"
    ;;
esac
